name: Kubescape

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nsa-security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | bash
          echo "$HOME/.kubescape" >> $GITHUB_PATH  # Add to PATH

      - name: Verify Kubescape Installation
        run: which kubescape || echo "Kubescape not installed"

      - name: Scan YAML files
        run: kubescape scan framework nsa *.yaml
