name: Kubescape

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nsa-security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | bash
          echo "$HOME/.kubescape" >> $GITHUB_PATH
          source $GITHUB_PATH

      - name: Verify Kubescape Installation
        run: |
          which kubescape || echo "Kubescape not found"
          ls -lah $HOME/.kubescape || echo "Kubescape directory not found"

      - name: Scan YAML files
        run: $HOME/.kubescape scan framework nsa *.yaml
